import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Box } from "@mui/material";
import Nav from "./components/nav";
import NewsStory from "./components/news-story";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* FIXME: Make flexdirection column on smaller screens and turn sidenav to appbar */}
        {/* Define layout with a left side Nav and a main content Box */}

        <Box
          sx={{
            display: "flex",
            flexDirection: "row",
          }}
        >
          {/* Left side Nav */}
          <Nav />

          {/* Main Content */}
          <Box
            sx={{
              flex: 1,
              display: "flex",
              flexDirection: "column",
              height: "100vh",
              overflowY: "auto",
              overflowX: "hidden",
            }}
          >
            {children}
          </Box>
        </Box>
      </body>
    </html>
  );
};

export default RootLayout;
